dbt_chess:
  target: dev
  outputs:
    local:
      dataset: dbt_filiplivancic
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: checkmate-453316
      threads: 4
      type: bigquery

    dev:
      dataset: dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: checkmate-453316
      threads: 4
      type: bigquery

    prod:
      dataset: prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: checkmate-453316
      threads: 4
      type: bigquery

    airflow:
      dataset: dev
      type: bigquery
      method: service-account
      keyfile: /keys/checkmate-airflow.json
      project: checkmate-453316
      location: EU
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
